Gemfile, Gemfile.lock, app/models/user.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20211115151902_devise_create_users.rb, db/migrate/20211115152009_add_column_to_user.rb, db/schema.rb, test/models/user_test.rb
Issues with the db when doing user table
=> fix the db issues

app/models/service.rb, db/migrate/20211115154425_create_services.rb, db/migrate/20211115154618_add_column_to_service.rb, db/schema.rb, test/models/service_test.rb
Creation de la table et ajout des colonnes "service"
=> ajout du model service

app/controllers/application_controller.rb, app/models/intervention.rb, app/models/service.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, db/migrate/20211115154314_create_interventions.rb, db/migrate/20211115161952_add_column_to_intervention.rb, db/schema.rb, test/models/intervention_test.rb
- Ajout de la table intervention
- Modif pour Devise (formulaire + permit params)
=> Create intervention model

app/controllers/services_controller.rb, app/views/services/index.html.erb, config/routes.rb, db/migrate/20211116102431_add_title_to_service.rb, db/schema.rb, test/controllers/services_controller_test.rb
- Added title to service table
- Index route pour services
- Controller services
- Index page (html)
=> Add title to service, controller services and index services

.gitignore
=> ajout de git ignore

app/controllers/services_controller.rb, app/policies/service_policy.rb, app/views/services/edit.html.erb, app/views/services/index.html.erb, app/views/services/new.html.erb, app/views/services/show.html.erb, config/routes.rb, db/migrate/20211116114434_rename_speciality_column.rb, db/schema.rb, db/seeds.rb, test/policies/service_policy_test.rb
- Toutes les routes de Services
- Toutes les actions de Services
- Toutes les vues de Services
- Adaptation à Pundit
=> Add show services

.gitignore
=> added cloudinary API key

app/views/layouts/application.html.erb
=> added the right link on the navbar

app/assets/stylesheets/components/_banner.scss, app/views/pages/home.html.erb
=> changed the cta

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/controllers/services_controller.rb, app/views/services/index.html.erb
- Button primary to Add a service
- Link to show a service
- Cards to put the index
=> front index Services

app/controllers/interventions_controller.rb, app/policies/intervention_policy.rb, app/views/interventions/edit.html.erb, app/views/interventions/index.html.erb, app/views/interventions/new.html.erb, app/views/interventions/show.html.erb, app/views/services/edit.html.erb, app/views/services/new.html.erb, app/views/services/show.html.erb, config/routes.rb, db/migrate/20211117102234_add_column_description_to_intervention.rb, db/migrate/20211117102619_rename_description_to_presentation_in_services.rb, db/schema.rb, test/controllers/interventions_controller_test.rb
- Création du controller Interventions
- Modification de description en présentations dans services
- Création des fichiers html edit, show, index et new
=> Add controller interventions

app/views/services/index.html.erb
Modification de description en presentation
=> Changement de description en presentation

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_log_in.scss, app/views/devise/sessions/new.html.erb
=> log-in front

app/views/services/show.html.erb
- Banner for the service
- Button to create intervention
- Prettify page
=> done front show service

app/views/layouts/application.html.erb
Ajout du lien entre mes interventions et mes interventions
=> Ajout du lien entre Mes interventions et la page intervention

app/views/services/index.html.erb
=> change title

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_new_service.scss, app/views/services/edit.html.erb, app/views/services/new.html.erb
Front du new et edit du service
=> front_edit_new_service

app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb
Mise en fonction de la dropdown list
=> Mise en fonction de la dropdown list

app/views/pages/home.html.erb
Added some content  on the home page!
=> Add some content

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_new_intervention.scss, app/views/interventions/edit.html.erb, app/views/interventions/new.html.erb
front du edit et new d'intervention
=> front_edit_new_intervention

app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb
- Bouton deconnexion opérationnel
- Bouton log in visible si pas connecté
=> Ajout de la fonction deconnexion et log in

app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb
=> button login front

app/controllers/interventions_controller.rb, app/controllers/services_controller.rb, app/views/interventions/new.html.erb, db/seeds.rb
=> rien de fou

app/controllers/services_controller.rb, app/views/services/edit.html.erb
=> Transfert vers edit

app/controllers/services_controller.rb, app/views/pages/home.html.erb, app/views/services/show.html.erb
Changed Index services controller and index.html.erb, in order to filter the services according to the dropdown search
=> filtering services done

app/views/services/show.html.erb
=> big mistake fix

db/migrate/20211115161952_add_column_to_intervention.rb, db/migrate/20211118100102_change_column_new_services_presentation.rb, db/migrate/20211118101305_change_column_interventions_description.rb, db/schema.rb
Changement de classe des presentation, description, et date
=> Changement de classe des presentation, description, et date

app/views/services/show.html.erb
=> done front

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/javascript/controllers/geocoder_controller.js, app/javascript/controllers/mapbox_controller.js, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/services/new.html.erb, package.json, yarn.lock
correction faute ortho
ajout d'un footer (a redesign)
ajout de l'autocompleat sur la loc
=> ptit changement

app/controllers/interventions_controller.rb, db/schema.rb
For the my intervention dash, filter on the current user
=> filter on the right user

app/views/interventions/show.html.erb, config/routes.rb
Resources interventions remontée de 4 lignes
Ajout d'un bouton back pour revenir à l'index interventions
=> Ajout d'un bouton back

app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, db/schema.rb
Ajout du bouton add a service
Bouton mes interventions ajouté dans la navbar et retiré de la dropdown list
=> ajout du bouton en dehors de la navbar et ajout du bouton add a service

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/views/interventions/new.html.erb, app/views/services/edit.html.erb, app/views/services/index.html.erb, app/views/services/new.html.erb, app/views/services/show.html.erb, db/schema.rb
Front des boutons add, edit, create, delete
=> Button front

app/controllers/services_controller.rb, app/views/interventions/index.html.erb, app/views/interventions/show.html.erb, config/routes.rb
Intervention index page pimped
=> index intervention done

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_navbar.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
Couleur et front du form signup + bouton login
=> front bouton + signup

app/views/layouts/application.html.erb, db/schema.rb
Mise en place de deux boutons avec un lien a et pas link_to à revoir
=> Ajout de deux boutons à revoir

db/migrate/20211118143527_remove_column_date.rb, db/migrate/20211118143732_add_column_intervention_date.rb, db/schema.rb
Changement du format date dans intervention
=> Changement du format de la date

app/assets/stylesheets/components/_container.scss, app/views/interventions/index.html.erb, app/views/interventions/show.html.erb, app/views/layouts/application.html.erb
La page show d'une intervention est nice
=> show d'une intervention bg

app/views/services/index.html.erb
=> index fixed

app/views/interventions/edit.html.erb, app/views/interventions/new.html.erb
=> better forms

app/models/service.rb, app/views/services/new.html.erb
Ajout de la dropdownlist dans services new
=> Ajout de la dropdown list dans services new

app/assets/stylesheets/components/_footer.scss
- Changement de couleur du footer
- footex fixe en bas de la page
=> Footer fixe en bas et changement de couleur

app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_navbar.scss, app/controllers/interventions_controller.rb, app/controllers/services_controller.rb, app/policies/service_policy.rb, app/views/interventions/_info_window.html.erb, app/views/layouts/application.html.erb, app/views/services/_info_window.html.erb, app/views/services/_info_window_service.html.erb, app/views/services/_info_window_user.html.erb
site responsive
problème de la map fix avec un peu de refacto
=> responsive+map

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/services/index.html.erb
- Changement couleur background
- Changement couleur index services
- Ajout d'ombrage index services
- footer fixé en bas
=> Changement couleur background + index de services

app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
=> Fix du body et du footer

app/views/services/edit.html.erb, app/views/services/new.html.erb
Ajout d'une shadow box dans new services
=> Ajout d'une shadow box dans new services

app/views/interventions/new.html.erb
Changement format new interventions
=> Changement format new interventions

app/views/services/show.html.erb
=> Map margé et shadowboxé

app/views/services/show.html.erb
Ajout de la confirmation du delete
=> Ajout de la confirmation pour le delete

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/views/pages/home.html.erb, app/views/services/show.html.erb
taille du text
couleurs des onglets
=> colors and text
